### PR TITLE
Convert things to ARC and modern ObjC Style

### LINKED ISSUE #2: Modernize code by converting MRC to ARC
Manual reference counting is so passé.

### PR DESCRIPTION
**Pull request by lyricsboy**
- takes advantage of ARC
- prefers property access to ivars

Fixes #2

### CODE REVIEW

**Comment by lyricsboy** [comment]
@natechan if you could take a look at this I'd appreciate it. It might be easier to merge this before anything else since it touches lots of code.

I'm confident there are additional places where we can modernize syntax, but I was going for a minimalist approach here.

**Comment by natechan** [comment]
Would be nice to see things like

``` objc
Step *step = (Step *)[self.arrayController arrangedObjects][selectedRow];
```

and

``` objc
@[[Step class]]
```

changed to use dot notation

``` objc
Step *step = (Step *)self.arrayController.arrangedObjects[selectedRow];
```

``` objc
@[Step.class]
```

Would also be really nice to see implicit types 

``` objc
- (IBAction)showPreferences:sender;
```

replaced with explicit types:

``` objc
- (IBAction)showPreferences:(id)sender;
```

even if those explicit types are only `id`.

The PR is good as it is and I'm happy to merge it (once the two minor comments are addressed).  We should probably either keep https://github.com/bignerdranch/DemoMonkey/issues/2 open or open other issues around these changes and others like them.

**Comment by lyricsboy** [comment]
Agreed on the dot notation, but unfortunately NSArrayController -arrangedObjects is typed `id`! So using dot notation without excessive casting makes the compiler mad.

I can't believe anyone gets anything done in Cocoa :)

**Comment by natechan** [comment]
Can work around this by throwing a `bnr_arrangedObjects` property which is typed appropriately into a category on NSArrayController.  Setting this particular example aside, there are many other cases where dot notation would be preferable.

**Pull request merged**
