### PR TITLE
Persist either to XML or Archive.

### PR DESCRIPTION
**Pull request by natechan**
Previously, the app only persisted to an archive.  That makes version control sad.

But this PR makes version control happy because it now allows the user to serialize to XML.

### CODE REVIEW

**Comment by lyricsboy** [comment]
Is it possible to use the same extension for both file types and distinguish them using the mime type or something else instead? I think OmniGraffle supports this somehow (you can save a .graffle as a package or a flat file).

**Comment by lyricsboy** [comment]
Closes #3

**Comment by natechan** [comment]
@lyricsboy Changed to use the same extension for both files formats in https://github.com/bignerdranch/DemoMonkey/commit/6cb8df50c5268248c97593ba1f2916ddb8ac8c3e .

**Comment by lyricsboy** [comment]
This is awesome! Not too nasty a hack to get the multiple formats for a single extension.

**Comment by natechan** [comment]
@lyricsboy The hacking is not yet complete, sadly.

**Pull request closed without merging**
